//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace PerformanceReportCS
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "TuneReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "TuneReport", IsNullable = false)]
    public partial class TuneReportDataSet
    {

        private TuneReportDataSetTuneReport[] tuneReportField;

        private TuneReportDataSetTuneReportItem[] tuneReportItemField;

        private TuneReportDataSetTuneElement[] tuneElementField;

        private TuneReportDataSetTuneParameter[] tuneParameterField;

        private TuneReportDataSetMeter[] meterField;

        private string schemaVersionField;

        private string dataVersionField;

        private string sIVersionField;

        private string auditTrailField;

        private string batchNameField;

        private string batchDataPathField;

        private string qCDataPathField;

        private string hashCodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TuneReport")]
        public TuneReportDataSetTuneReport[] TuneReport
        {
            get
            {
                return this.tuneReportField;
            }
            set
            {
                this.tuneReportField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TuneReportItem")]
        public TuneReportDataSetTuneReportItem[] TuneReportItem
        {
            get
            {
                return this.tuneReportItemField;
            }
            set
            {
                this.tuneReportItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TuneElement")]
        public TuneReportDataSetTuneElement[] TuneElement
        {
            get
            {
                return this.tuneElementField;
            }
            set
            {
                this.tuneElementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TuneParameter")]
        public TuneReportDataSetTuneParameter[] TuneParameter
        {
            get
            {
                return this.tuneParameterField;
            }
            set
            {
                this.tuneParameterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Meter")]
        public TuneReportDataSetMeter[] Meter
        {
            get
            {
                return this.meterField;
            }
            set
            {
                this.meterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SchemaVersion
        {
            get
            {
                return this.schemaVersionField;
            }
            set
            {
                this.schemaVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DataVersion
        {
            get
            {
                return this.dataVersionField;
            }
            set
            {
                this.dataVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SIVersion
        {
            get
            {
                return this.sIVersionField;
            }
            set
            {
                this.sIVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AuditTrail
        {
            get
            {
                return this.auditTrailField;
            }
            set
            {
                this.auditTrailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BatchName
        {
            get
            {
                return this.batchNameField;
            }
            set
            {
                this.batchNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BatchDataPath
        {
            get
            {
                return this.batchDataPathField;
            }
            set
            {
                this.batchDataPathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string QCDataPath
        {
            get
            {
                return this.qCDataPathField;
            }
            set
            {
                this.qCDataPathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HashCode
        {
            get
            {
                return this.hashCodeField;
            }
            set
            {
                this.hashCodeField = value;
            }
        }
    }

    /// <remarks/>
    /// 
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlType(AnonymousType = true, Namespace = "TuneReport")]
    [System.Xml.Serialization.XmlRoot("TuneReport")]
    public partial class TuneReportDataSetTuneReport
    {

        private string tuneReportIDField;

        private string reportSetIDField;

        private string versionField;

        private string createdField;

        private string tuneModeField;

        private string nebulizerTypeField;

        private string torchTypeField;

        private string checkOutField;

        private string modelNameField;

        private string serialNumberField;

        private string tuneReportNumberField;

        private string lensesModelField;

        /// <remarks/>
        public string TuneReportID
        {
            get
            {
                return this.tuneReportIDField;
            }
            set
            {
                this.tuneReportIDField = value;
            }
        }

        /// <remarks/>
        public string ReportSetID
        {
            get
            {
                return this.reportSetIDField;
            }
            set
            {
                this.reportSetIDField = value;
            }
        }

        /// <remarks/>
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public string Created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }

        /// <remarks/>
        public string TuneMode
        {
            get
            {
                return this.tuneModeField;
            }
            set
            {
                this.tuneModeField = value;
            }
        }

        /// <remarks/>
        public string NebulizerType
        {
            get
            {
                return this.nebulizerTypeField;
            }
            set
            {
                this.nebulizerTypeField = value;
            }
        }

        /// <remarks/>
        public string TorchType
        {
            get
            {
                return this.torchTypeField;
            }
            set
            {
                this.torchTypeField = value;
            }
        }

        /// <remarks/>
        public string CheckOut
        {
            get
            {
                return this.checkOutField;
            }
            set
            {
                this.checkOutField = value;
            }
        }

        /// <remarks/>
        public string ModelName
        {
            get
            {
                return this.modelNameField;
            }
            set
            {
                this.modelNameField = value;
            }
        }

        /// <remarks/>
        public string SerialNumber
        {
            get
            {
                return this.serialNumberField;
            }
            set
            {
                this.serialNumberField = value;
            }
        }

        /// <remarks/>
        public string TuneReportNumber
        {
            get
            {
                return this.tuneReportNumberField;
            }
            set
            {
                this.tuneReportNumberField = value;
            }
        }

        /// <remarks/>
        public string LensesModel
        {
            get
            {
                return this.lensesModelField;
            }
            set
            {
                this.lensesModelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "TuneReport")]
    public partial class TuneReportDataSetTuneReportItem
    {

        private string tuneReportIDField;

        private string reportSetIDField;

        private string reportItemIDField;

        private string tuneItemTypeField;

        private string integTimeField;

        private string acquisitionTimeField;

        private string samplingPeriodField;

        /// <remarks/>
        public string TuneReportID
        {
            get
            {
                return this.tuneReportIDField;
            }
            set
            {
                this.tuneReportIDField = value;
            }
        }

        /// <remarks/>
        public string ReportSetID
        {
            get
            {
                return this.reportSetIDField;
            }
            set
            {
                this.reportSetIDField = value;
            }
        }

        /// <remarks/>
        public string ReportItemID
        {
            get
            {
                return this.reportItemIDField;
            }
            set
            {
                this.reportItemIDField = value;
            }
        }

        /// <remarks/>
        public string TuneItemType
        {
            get
            {
                return this.tuneItemTypeField;
            }
            set
            {
                this.tuneItemTypeField = value;
            }
        }

        /// <remarks/>
        public string IntegTime
        {
            get
            {
                return this.integTimeField;
            }
            set
            {
                this.integTimeField = value;
            }
        }

        /// <remarks/>
        public string AcquisitionTime
        {
            get
            {
                return this.acquisitionTimeField;
            }
            set
            {
                this.acquisitionTimeField = value;
            }
        }

        /// <remarks/>
        public string SamplingPeriod
        {
            get
            {
                return this.samplingPeriodField;
            }
            set
            {
                this.samplingPeriodField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "TuneReport")]
    public partial class TuneReportDataSetTuneElement
    {

        private string tuneReportIDField;

        private string reportSetIDField;

        private string reportItemIDField;

        private string tuneElementIDField;

        private string mzField;

        private string heightField;

        private string axisField;

        private string width10Field;

        private string width10PosXField;

        private string width10PosYField;

        private string width50Field;

        private string width50PosXField;

        private string width50PosYField;

        private string countField;

        private string rsdField;

        private string convertedXValuesField;

        private string convertedYValuesField;

        /// <remarks/>
        public string TuneReportID
        {
            get
            {
                return this.tuneReportIDField;
            }
            set
            {
                this.tuneReportIDField = value;
            }
        }

        /// <remarks/>
        public string ReportSetID
        {
            get
            {
                return this.reportSetIDField;
            }
            set
            {
                this.reportSetIDField = value;
            }
        }

        /// <remarks/>
        public string ReportItemID
        {
            get
            {
                return this.reportItemIDField;
            }
            set
            {
                this.reportItemIDField = value;
            }
        }

        /// <remarks/>
        public string TuneElementID
        {
            get
            {
                return this.tuneElementIDField;
            }
            set
            {
                this.tuneElementIDField = value;
            }
        }

        /// <remarks/>
        public string MZ
        {
            get
            {
                return this.mzField;
            }
            set
            {
                this.mzField = value;
            }
        }

        /// <remarks/>
        public string Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>
        public string Axis
        {
            get
            {
                return this.axisField;
            }
            set
            {
                this.axisField = value;
            }
        }

        /// <remarks/>
        public string Width10
        {
            get
            {
                return this.width10Field;
            }
            set
            {
                this.width10Field = value;
            }
        }

        /// <remarks/>
        public string Width10PosX
        {
            get
            {
                return this.width10PosXField;
            }
            set
            {
                this.width10PosXField = value;
            }
        }

        /// <remarks/>
        public string Width10PosY
        {
            get
            {
                return this.width10PosYField;
            }
            set
            {
                this.width10PosYField = value;
            }
        }

        /// <remarks/>
        public string Width50
        {
            get
            {
                return this.width50Field;
            }
            set
            {
                this.width50Field = value;
            }
        }

        /// <remarks/>
        public string Width50PosX
        {
            get
            {
                return this.width50PosXField;
            }
            set
            {
                this.width50PosXField = value;
            }
        }

        /// <remarks/>
        public string Width50PosY
        {
            get
            {
                return this.width50PosYField;
            }
            set
            {
                this.width50PosYField = value;
            }
        }

        /// <remarks/>
        public string Count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }

        /// <remarks/>
        public string Rsd
        {
            get
            {
                return this.rsdField;
            }
            set
            {
                this.rsdField = value;
            }
        }

        /// <remarks/>
        public string ConvertedXValues
        {
            get
            {
                return this.convertedXValuesField;
            }
            set
            {
                this.convertedXValuesField = value;
            }
        }

        /// <remarks/>
        public string ConvertedYValues
        {
            get
            {
                return this.convertedYValuesField;
            }
            set
            {
                this.convertedYValuesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "TuneReport")]
    public partial class TuneReportDataSetTuneParameter
    {

        private string tuneReportIDField;

        private string reportSetIDField;

        private string tuneParamIDField;

        private string nameField;

        private string valueField;

        /// <remarks/>
        public string TuneReportID
        {
            get
            {
                return this.tuneReportIDField;
            }
            set
            {
                this.tuneReportIDField = value;
            }
        }

        /// <remarks/>
        public string ReportSetID
        {
            get
            {
                return this.reportSetIDField;
            }
            set
            {
                this.reportSetIDField = value;
            }
        }

        /// <remarks/>
        public string TuneParamID
        {
            get
            {
                return this.tuneParamIDField;
            }
            set
            {
                this.tuneParamIDField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "TuneReport")]
    public partial class TuneReportDataSetMeter
    {

        private string tuneReportIDField;

        private string reportSetIDField;

        private string reportMeterIDField;

        private string nameField;

        private string valueField;

        private string unitField;

        /// <remarks/>
        public string TuneReportID
        {
            get
            {
                return this.tuneReportIDField;
            }
            set
            {
                this.tuneReportIDField = value;
            }
        }

        /// <remarks/>
        public string ReportSetID
        {
            get
            {
                return this.reportSetIDField;
            }
            set
            {
                this.reportSetIDField = value;
            }
        }

        /// <remarks/>
        public string ReportMeterID
        {
            get
            {
                return this.reportMeterIDField;
            }
            set
            {
                this.reportMeterIDField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        public string Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "TuneReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "TuneReport", IsNullable = false)]
    public partial class NewDataSet
    {

        private TuneReportDataSet[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TuneReportDataSet")]
        public TuneReportDataSet[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
}

