//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace TuneBatch
{



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "IcpMS")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "IcpMS", IsNullable = false)]
    public partial class AcqReportDataSet
    {

        private AcqReportDataSetTune[] itemsField;

        private int acqReportSchemaVersionField;

        private bool acqReportSchemaVersionFieldSpecified;

        private string batchCommentField;

        private string batchFolderField;

        private string modelNameField;

        private string nebulizerTypeField;

        private string reportCommentField;

        private short reportVersionField;

        private bool reportVersionFieldSpecified;

        private string serialNumberField;

        private string torchTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Tune")]
        public AcqReportDataSetTune[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int AcqReportSchemaVersion
        {
            get
            {
                return this.acqReportSchemaVersionField;
            }
            set
            {
                this.acqReportSchemaVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AcqReportSchemaVersionSpecified
        {
            get
            {
                return this.acqReportSchemaVersionFieldSpecified;
            }
            set
            {
                this.acqReportSchemaVersionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BatchComment
        {
            get
            {
                return this.batchCommentField;
            }
            set
            {
                this.batchCommentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BatchFolder
        {
            get
            {
                return this.batchFolderField;
            }
            set
            {
                this.batchFolderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ModelName
        {
            get
            {
                return this.modelNameField;
            }
            set
            {
                this.modelNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NebulizerType
        {
            get
            {
                return this.nebulizerTypeField;
            }
            set
            {
                this.nebulizerTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReportComment
        {
            get
            {
                return this.reportCommentField;
            }
            set
            {
                this.reportCommentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short ReportVersion
        {
            get
            {
                return this.reportVersionField;
            }
            set
            {
                this.reportVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReportVersionSpecified
        {
            get
            {
                return this.reportVersionFieldSpecified;
            }
            set
            {
                this.reportVersionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SerialNumber
        {
            get
            {
                return this.serialNumberField;
            }
            set
            {
                this.serialNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TorchType
        {
            get
            {
                return this.torchTypeField;
            }
            set
            {
                this.torchTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "IcpMS")]
    public partial class AcqReportDataSetTune
    {

        private short tuneIDField;

        private int tuneStepField;

        private bool tuneStepFieldSpecified;

        private string tuneModeNameField;

        private string graphicSensitivityField;

        private string graphicResolutionAxisField;

        private string graphicResolutionAxisQ1Field;

        private string graphicSpacingField;

        private AcqReportDataSetTuneTuneParameter[] tuneParameterField;

        private AcqReportDataSetTuneCategory[] categoryField;

        private AcqReportDataSetTuneMeter[] meterField;

        /// <remarks/>
        public short TuneID
        {
            get
            {
                return this.tuneIDField;
            }
            set
            {
                this.tuneIDField = value;
            }
        }

        /// <remarks/>
        public int TuneStep
        {
            get
            {
                return this.tuneStepField;
            }
            set
            {
                this.tuneStepField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TuneStepSpecified
        {
            get
            {
                return this.tuneStepFieldSpecified;
            }
            set
            {
                this.tuneStepFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string TuneModeName
        {
            get
            {
                return this.tuneModeNameField;
            }
            set
            {
                this.tuneModeNameField = value;
            }
        }

        /// <remarks/>
        public string GraphicSensitivity
        {
            get
            {
                return this.graphicSensitivityField;
            }
            set
            {
                this.graphicSensitivityField = value;
            }
        }

        /// <remarks/>
        public string GraphicResolutionAxis
        {
            get
            {
                return this.graphicResolutionAxisField;
            }
            set
            {
                this.graphicResolutionAxisField = value;
            }
        }

        /// <remarks/>
        public string GraphicResolutionAxisQ1
        {
            get
            {
                return this.graphicResolutionAxisQ1Field;
            }
            set
            {
                this.graphicResolutionAxisQ1Field = value;
            }
        }

        /// <remarks/>
        public string GraphicSpacing
        {
            get
            {
                return this.graphicSpacingField;
            }
            set
            {
                this.graphicSpacingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TuneParameter")]
        public AcqReportDataSetTuneTuneParameter[] TuneParameter
        {
            get
            {
                return this.tuneParameterField;
            }
            set
            {
                this.tuneParameterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Category")]
        public AcqReportDataSetTuneCategory[] Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Meter")]
        public AcqReportDataSetTuneMeter[] Meter
        {
            get
            {
                return this.meterField;
            }
            set
            {
                this.meterField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "IcpMS")]
    public partial class AcqReportDataSetTuneTuneParameter
    {

        private short tuneIDField;

        private short parameterIDField;

        private string parameterGroupField;

        private string parameterNameField;

        private object valueField;

        private string unitField;

        /// <remarks/>
        public short TuneID
        {
            get
            {
                return this.tuneIDField;
            }
            set
            {
                this.tuneIDField = value;
            }
        }

        /// <remarks/>
        public short ParameterID
        {
            get
            {
                return this.parameterIDField;
            }
            set
            {
                this.parameterIDField = value;
            }
        }

        /// <remarks/>
        public string ParameterGroup
        {
            get
            {
                return this.parameterGroupField;
            }
            set
            {
                this.parameterGroupField = value;
            }
        }

        /// <remarks/>
        public string ParameterName
        {
            get
            {
                return this.parameterNameField;
            }
            set
            {
                this.parameterNameField = value;
            }
        }

        /// <remarks/>
        public object Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        public string Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "IcpMS")]
    public partial class AcqReportDataSetTuneCategory
    {

        private short tuneIDField;

        private short categoryIDField;

        private string categoryField;

        private double peakHeightXPercentField;

        private bool peakHeightXPercentFieldSpecified;

        private double integrationTimeField;

        private bool integrationTimeFieldSpecified;

        private double samplingPeriodField;

        private bool samplingPeriodFieldSpecified;

        private double acquisitionTimeField;

        private bool acquisitionTimeFieldSpecified;

        private string yAxisScaleField;

        private string scanTypeField;

        private string peakProfileField;

        private AcqReportDataSetTuneCategoryResult[] resultField;

        /// <remarks/>
        public short TuneID
        {
            get
            {
                return this.tuneIDField;
            }
            set
            {
                this.tuneIDField = value;
            }
        }

        /// <remarks/>
        public short CategoryID
        {
            get
            {
                return this.categoryIDField;
            }
            set
            {
                this.categoryIDField = value;
            }
        }

        /// <remarks/>
        public string Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        public double PeakHeightXPercent
        {
            get
            {
                return this.peakHeightXPercentField;
            }
            set
            {
                this.peakHeightXPercentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PeakHeightXPercentSpecified
        {
            get
            {
                return this.peakHeightXPercentFieldSpecified;
            }
            set
            {
                this.peakHeightXPercentFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double IntegrationTime
        {
            get
            {
                return this.integrationTimeField;
            }
            set
            {
                this.integrationTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IntegrationTimeSpecified
        {
            get
            {
                return this.integrationTimeFieldSpecified;
            }
            set
            {
                this.integrationTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double SamplingPeriod
        {
            get
            {
                return this.samplingPeriodField;
            }
            set
            {
                this.samplingPeriodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SamplingPeriodSpecified
        {
            get
            {
                return this.samplingPeriodFieldSpecified;
            }
            set
            {
                this.samplingPeriodFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double AcquisitionTime
        {
            get
            {
                return this.acquisitionTimeField;
            }
            set
            {
                this.acquisitionTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AcquisitionTimeSpecified
        {
            get
            {
                return this.acquisitionTimeFieldSpecified;
            }
            set
            {
                this.acquisitionTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string YAxisScale
        {
            get
            {
                return this.yAxisScaleField;
            }
            set
            {
                this.yAxisScaleField = value;
            }
        }

        /// <remarks/>
        public string ScanType
        {
            get
            {
                return this.scanTypeField;
            }
            set
            {
                this.scanTypeField = value;
            }
        }

        /// <remarks/>
        public string PeakProfile
        {
            get
            {
                return this.peakProfileField;
            }
            set
            {
                this.peakProfileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Result")]
        public AcqReportDataSetTuneCategoryResult[] Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "IcpMS")]
    public partial class AcqReportDataSetTuneCategoryResult
    {

        private short tuneIDField;

        private short categoryIDField;

        private short resultIDField;

        private int channelField;

        private bool channelFieldSpecified;

        private string massField;

        private double rangeField;

        private bool rangeFieldSpecified;

        private double latestCountField;

        private bool latestCountFieldSpecified;

        private double countField;

        private bool countFieldSpecified;

        private string countUnitField;

        private double responseField;

        private bool responseFieldSpecified;

        private bool responseCheckField;

        private bool responseCheckFieldSpecified;

        private double responseCheckMinField;

        private bool responseCheckMinFieldSpecified;

        private double responseRatioField;

        private bool responseRatioFieldSpecified;

        private bool responseRatioCheckField;

        private bool responseRatioCheckFieldSpecified;

        private double responseRatioCheckMinField;

        private bool responseRatioCheckMinFieldSpecified;

        private double responseRatioCheckMaxField;

        private bool responseRatioCheckMaxFieldSpecified;

        private double rSDField;

        private bool rSDFieldSpecified;

        private bool rSDCheckField;

        private bool rSDCheckFieldSpecified;

        private double rSDCheckMaxField;

        private bool rSDCheckMaxFieldSpecified;

        private double backgroundField;

        private bool backgroundFieldSpecified;

        private bool backgroundCheckField;

        private bool backgroundCheckFieldSpecified;

        private double backgroundCheckMaxField;

        private bool backgroundCheckMaxFieldSpecified;

        private double peakHeightField;

        private bool peakHeightFieldSpecified;

        private double axisField;

        private bool axisFieldSpecified;

        private bool axisCheckField;

        private bool axisCheckFieldSpecified;

        private double axisCheckMinField;

        private bool axisCheckMinFieldSpecified;

        private double axisCheckMaxField;

        private bool axisCheckMaxFieldSpecified;

        private double width50Field;

        private bool width50FieldSpecified;

        private double width10Field;

        private bool width10FieldSpecified;

        private double widthXField;

        private bool widthXFieldSpecified;

        private bool widthXCheckField;

        private bool widthXCheckFieldSpecified;

        private double widthXCheckMaxField;

        private bool widthXCheckMaxFieldSpecified;

        private AcqReportDataSetTuneCategoryResultReplicateData[] replicateDataField;

        /// <remarks/>
        public short TuneID
        {
            get
            {
                return this.tuneIDField;
            }
            set
            {
                this.tuneIDField = value;
            }
        }

        /// <remarks/>
        public short CategoryID
        {
            get
            {
                return this.categoryIDField;
            }
            set
            {
                this.categoryIDField = value;
            }
        }

        /// <remarks/>
        public short ResultID
        {
            get
            {
                return this.resultIDField;
            }
            set
            {
                this.resultIDField = value;
            }
        }

        /// <remarks/>
        public int Channel
        {
            get
            {
                return this.channelField;
            }
            set
            {
                this.channelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChannelSpecified
        {
            get
            {
                return this.channelFieldSpecified;
            }
            set
            {
                this.channelFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Mass
        {
            get
            {
                return this.massField;
            }
            set
            {
                this.massField = value;
            }
        }

        /// <remarks/>
        public double Range
        {
            get
            {
                return this.rangeField;
            }
            set
            {
                this.rangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RangeSpecified
        {
            get
            {
                return this.rangeFieldSpecified;
            }
            set
            {
                this.rangeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double LatestCount
        {
            get
            {
                return this.latestCountField;
            }
            set
            {
                this.latestCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatestCountSpecified
        {
            get
            {
                return this.latestCountFieldSpecified;
            }
            set
            {
                this.latestCountFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double Count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified
        {
            get
            {
                return this.countFieldSpecified;
            }
            set
            {
                this.countFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string CountUnit
        {
            get
            {
                return this.countUnitField;
            }
            set
            {
                this.countUnitField = value;
            }
        }

        /// <remarks/>
        public double Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResponseSpecified
        {
            get
            {
                return this.responseFieldSpecified;
            }
            set
            {
                this.responseFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool ResponseCheck
        {
            get
            {
                return this.responseCheckField;
            }
            set
            {
                this.responseCheckField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResponseCheckSpecified
        {
            get
            {
                return this.responseCheckFieldSpecified;
            }
            set
            {
                this.responseCheckFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double ResponseCheckMin
        {
            get
            {
                return this.responseCheckMinField;
            }
            set
            {
                this.responseCheckMinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResponseCheckMinSpecified
        {
            get
            {
                return this.responseCheckMinFieldSpecified;
            }
            set
            {
                this.responseCheckMinFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double ResponseRatio
        {
            get
            {
                return this.responseRatioField;
            }
            set
            {
                this.responseRatioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResponseRatioSpecified
        {
            get
            {
                return this.responseRatioFieldSpecified;
            }
            set
            {
                this.responseRatioFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool ResponseRatioCheck
        {
            get
            {
                return this.responseRatioCheckField;
            }
            set
            {
                this.responseRatioCheckField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResponseRatioCheckSpecified
        {
            get
            {
                return this.responseRatioCheckFieldSpecified;
            }
            set
            {
                this.responseRatioCheckFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double ResponseRatioCheckMin
        {
            get
            {
                return this.responseRatioCheckMinField;
            }
            set
            {
                this.responseRatioCheckMinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResponseRatioCheckMinSpecified
        {
            get
            {
                return this.responseRatioCheckMinFieldSpecified;
            }
            set
            {
                this.responseRatioCheckMinFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double ResponseRatioCheckMax
        {
            get
            {
                return this.responseRatioCheckMaxField;
            }
            set
            {
                this.responseRatioCheckMaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResponseRatioCheckMaxSpecified
        {
            get
            {
                return this.responseRatioCheckMaxFieldSpecified;
            }
            set
            {
                this.responseRatioCheckMaxFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double RSD
        {
            get
            {
                return this.rSDField;
            }
            set
            {
                this.rSDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RSDSpecified
        {
            get
            {
                return this.rSDFieldSpecified;
            }
            set
            {
                this.rSDFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool RSDCheck
        {
            get
            {
                return this.rSDCheckField;
            }
            set
            {
                this.rSDCheckField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RSDCheckSpecified
        {
            get
            {
                return this.rSDCheckFieldSpecified;
            }
            set
            {
                this.rSDCheckFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double RSDCheckMax
        {
            get
            {
                return this.rSDCheckMaxField;
            }
            set
            {
                this.rSDCheckMaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RSDCheckMaxSpecified
        {
            get
            {
                return this.rSDCheckMaxFieldSpecified;
            }
            set
            {
                this.rSDCheckMaxFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double Background
        {
            get
            {
                return this.backgroundField;
            }
            set
            {
                this.backgroundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BackgroundSpecified
        {
            get
            {
                return this.backgroundFieldSpecified;
            }
            set
            {
                this.backgroundFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool BackgroundCheck
        {
            get
            {
                return this.backgroundCheckField;
            }
            set
            {
                this.backgroundCheckField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BackgroundCheckSpecified
        {
            get
            {
                return this.backgroundCheckFieldSpecified;
            }
            set
            {
                this.backgroundCheckFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double BackgroundCheckMax
        {
            get
            {
                return this.backgroundCheckMaxField;
            }
            set
            {
                this.backgroundCheckMaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BackgroundCheckMaxSpecified
        {
            get
            {
                return this.backgroundCheckMaxFieldSpecified;
            }
            set
            {
                this.backgroundCheckMaxFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double PeakHeight
        {
            get
            {
                return this.peakHeightField;
            }
            set
            {
                this.peakHeightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PeakHeightSpecified
        {
            get
            {
                return this.peakHeightFieldSpecified;
            }
            set
            {
                this.peakHeightFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double Axis
        {
            get
            {
                return this.axisField;
            }
            set
            {
                this.axisField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AxisSpecified
        {
            get
            {
                return this.axisFieldSpecified;
            }
            set
            {
                this.axisFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool AxisCheck
        {
            get
            {
                return this.axisCheckField;
            }
            set
            {
                this.axisCheckField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AxisCheckSpecified
        {
            get
            {
                return this.axisCheckFieldSpecified;
            }
            set
            {
                this.axisCheckFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double AxisCheckMin
        {
            get
            {
                return this.axisCheckMinField;
            }
            set
            {
                this.axisCheckMinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AxisCheckMinSpecified
        {
            get
            {
                return this.axisCheckMinFieldSpecified;
            }
            set
            {
                this.axisCheckMinFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double AxisCheckMax
        {
            get
            {
                return this.axisCheckMaxField;
            }
            set
            {
                this.axisCheckMaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AxisCheckMaxSpecified
        {
            get
            {
                return this.axisCheckMaxFieldSpecified;
            }
            set
            {
                this.axisCheckMaxFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double Width50
        {
            get
            {
                return this.width50Field;
            }
            set
            {
                this.width50Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Width50Specified
        {
            get
            {
                return this.width50FieldSpecified;
            }
            set
            {
                this.width50FieldSpecified = value;
            }
        }

        /// <remarks/>
        public double Width10
        {
            get
            {
                return this.width10Field;
            }
            set
            {
                this.width10Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Width10Specified
        {
            get
            {
                return this.width10FieldSpecified;
            }
            set
            {
                this.width10FieldSpecified = value;
            }
        }

        /// <remarks/>
        public double WidthX
        {
            get
            {
                return this.widthXField;
            }
            set
            {
                this.widthXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WidthXSpecified
        {
            get
            {
                return this.widthXFieldSpecified;
            }
            set
            {
                this.widthXFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool WidthXCheck
        {
            get
            {
                return this.widthXCheckField;
            }
            set
            {
                this.widthXCheckField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WidthXCheckSpecified
        {
            get
            {
                return this.widthXCheckFieldSpecified;
            }
            set
            {
                this.widthXCheckFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double WidthXCheckMax
        {
            get
            {
                return this.widthXCheckMaxField;
            }
            set
            {
                this.widthXCheckMaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WidthXCheckMaxSpecified
        {
            get
            {
                return this.widthXCheckMaxFieldSpecified;
            }
            set
            {
                this.widthXCheckMaxFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReplicateData")]
        public AcqReportDataSetTuneCategoryResultReplicateData[] ReplicateData
        {
            get
            {
                return this.replicateDataField;
            }
            set
            {
                this.replicateDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "IcpMS")]
    public partial class AcqReportDataSetTuneCategoryResultReplicateData
    {

        private short tuneIDField;

        private short categoryIDField;

        private short resultIDField;

        private short replicateIDField;

        private int replicateField;

        private bool replicateFieldSpecified;

        private double repCountField;

        private bool repCountFieldSpecified;

        /// <remarks/>
        public short TuneID
        {
            get
            {
                return this.tuneIDField;
            }
            set
            {
                this.tuneIDField = value;
            }
        }

        /// <remarks/>
        public short CategoryID
        {
            get
            {
                return this.categoryIDField;
            }
            set
            {
                this.categoryIDField = value;
            }
        }

        /// <remarks/>
        public short ResultID
        {
            get
            {
                return this.resultIDField;
            }
            set
            {
                this.resultIDField = value;
            }
        }

        /// <remarks/>
        public short ReplicateID
        {
            get
            {
                return this.replicateIDField;
            }
            set
            {
                this.replicateIDField = value;
            }
        }

        /// <remarks/>
        public int Replicate
        {
            get
            {
                return this.replicateField;
            }
            set
            {
                this.replicateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReplicateSpecified
        {
            get
            {
                return this.replicateFieldSpecified;
            }
            set
            {
                this.replicateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double RepCount
        {
            get
            {
                return this.repCountField;
            }
            set
            {
                this.repCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RepCountSpecified
        {
            get
            {
                return this.repCountFieldSpecified;
            }
            set
            {
                this.repCountFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "IcpMS")]
    public partial class AcqReportDataSetTuneMeter
    {

        private short tuneIDField;

        private short meterIDField;

        private string meterNameField;

        private string valueField;

        private string unitField;

        /// <remarks/>
        public short TuneID
        {
            get
            {
                return this.tuneIDField;
            }
            set
            {
                this.tuneIDField = value;
            }
        }

        /// <remarks/>
        public short MeterID
        {
            get
            {
                return this.meterIDField;
            }
            set
            {
                this.meterIDField = value;
            }
        }

        /// <remarks/>
        public string MeterName
        {
            get
            {
                return this.meterNameField;
            }
            set
            {
                this.meterNameField = value;
            }
        }

        /// <remarks/>
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        public string Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }
    }
}